version: '3'
services:
  db:
    build: ./db
    container_name: world-db
    restart: always
    ports:
      - "33060:3306"

  app:
    build: .
    container_name: world-app
    depends_on:
      - db
