version: '3.9'

services:
  app:
    build: .
    container_name: myapp
    depends_on:
      - mongo-dbserver
    environment:
      MONGO_URL: mongodb://mongo-dbserver:27017

  db:
    build: db/.
    restart: always
    ports:
      - "33060:3306"

  mongo-dbserver:
    image: mongo:latest
    container_name: mongo-dbserver
    ports:
      - "27017:27017"
